version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - OPENAI_API_KEY=your-secret-key
      - DATABASE_URL=postgresql://user:password@db:5432/hackscope
      - OPENAI_API_KEY=your-openai-api-key
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hackscope
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: